---
title: "MVCO cruise list packaging workflow"
author: "Kate Morkeski"
date: "2023-01-24"
output: html_notebook
---

Libraries used

```{r}
# two of the required packages are installed from GitHub
#library(remotes)
# remotes::install_github("EDIorg/EMLassemblyline")
#remotes::install_github("WHOIGit/ediutilities")

library(EMLassemblyline)
library(ediutilities)
library(here)
library(lubridate)
library(readxl)

```

Read data table

```{r}

events <- read_excel(here('List of MVCO cruises for NES-LTER project 20230124.xlsx'), sheet = 1, skip = 6)


```

Update and write data table

```{r}

events$date = ymd(events$date)

# remove rows after 2022-05-06 and columns for MVCO event number, Google Drive links, and alternate DLA links
events <- events[-c(82:99),-c(2,6, 8)]

# rename cols to lowercase
colnames(events)[10] <- "bucket_sample"
colnames(events)[11] <- "bongo_or_other_net"

# rename Notes to comment
colnames(events)[12] <- "comment"

write.csv(events, 'nes-lter-events-mvco.csv', row.names = FALSE)

```

Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}

excel_to_template(here('List of MVCO cruises for NES-LTER project 20230124'), 'nes-lter-events-mvco', rights='CC0')

```


Generate the package and insert the parent project node into the resulting EML

```{r}

pkg_id <- 'knb-lter-nes.22.1'

make_eml(here(),
         dataset.title= "Event logs from Northeast U.S. Shelf Long Term Ecological Research (NES-LTER) cruises to the Martha's Vineyard Coastal Observatory ongoing since 2017",
         data.table='nes-lter-events-mvco.csv',
         data.table.description='List of cruises to MVCO and data types collected',
         data.table.name = 'nes-lter-events-mvco',
         temporal.coverage = temporal_coverage(events$date),
         geographic.description = "Martha's Vineyard Coastal Observatory",
         geographic.coordinates = geographic_coordinates(41.325, 70.567),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

project_insert(pkg_id)

```
